services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend1
      - backend2
      - backend3
      - websocket
    networks:
      - ereuna-network
    volumes:
      - ./certs:/etc/nginx/certs:ro

  backend1:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "5500:5500"
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/EreunaDB
    volumes:
      - ./certs:/app/certs:ro
    networks:
      - ereuna-network-internal
      - ereuna-network
    restart: unless-stopped

  backend2:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "5501:5500"
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/EreunaDB
    volumes:
      - ./certs:/app/certs:ro
    networks:
      - ereuna-network-internal
      - ereuna-network
    restart: unless-stopped

  backend3:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "5502:5500"
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/EreunaDB
    volumes:
      - ./certs:/app/certs:ro
    networks:
      - ereuna-network-internal
      - ereuna-network
    restart: unless-stopped

  websocket:
    build:
      context: .
      dockerfile: Dockerfile.websocket
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/EreunaDB
      - VITE_EREUNA_KEY=${VITE_EREUNA_KEY}
    volumes:
      - ./certs:/certs:ro
    networks:
      - ereuna-network-internal
      - ereuna-network
    restart: unless-stopped

  mongodb:
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db
      - ./mongodb-init:/docker-entrypoint-initdb.d
    environment:
      - MONGO_INITDB_DATABASE=EreunaDB
    networks:
      - ereuna-network-internal
    restart: unless-stopped
    expose:
      - "27017"

networks:
  ereuna-network-internal:
    driver: bridge
    internal: true
  ereuna-network:
    driver: bridge

volumes:
  mongodb_data:
