services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend1
      - backend2
      - backend3
      - websocket
    networks:
      - ereuna-network
    volumes:
      - ./certs:/etc/nginx/certs:ro

  backend1:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "5500:5500"
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/EreunaDB
    volumes:
      - ./certs:/app/certs:ro
    networks:
      - ereuna-network-internal
      - ereuna-network
    restart: unless-stopped

  backend2:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "5501:5500"
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/EreunaDB
    volumes:
      - ./certs:/app/certs:ro
    networks:
      - ereuna-network-internal
      - ereuna-network
    restart: unless-stopped

  backend3:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "5502:5500"
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/EreunaDB
    volumes:
      - ./certs:/app/certs:ro
    networks:
      - ereuna-network-internal
      - ereuna-network
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    command: [ "redis-server", "--save", "900", "1" ]
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 2s
      retries: 5
      start_period: 5s
    volumes:
      - redis_data:/data
    networks:
      - ereuna-network-internal
    restart: unless-stopped

  ingestor:
    build:
      context: .
      dockerfile: Dockerfile.injestor
    ports:
      - "8001:8000"
    depends_on:
      - mongodb
      - redis
    environment:
      - MONGO_URI=mongodb://mongodb:27017/EreunaDB
      - REDIS_URL=redis://redis:6379/0
      - VITE_EREUNA_KEY=${VITE_EREUNA_KEY}
    env_file:
      - ./.env
    volumes:
      - ./certs:/certs:ro
    networks:
      - ereuna-network-internal
      - ereuna-network
    restart: unless-stopped

  aggregator:
    build:
      context: .
      dockerfile: Dockerfile.aggregator
    depends_on:
      - redis
      - mongodb
    environment:
      - REDIS_URL=redis://redis:6379/0
      - MONGO_URI=mongodb://mongodb:27017/EreunaDB
    networks:
      - ereuna-network-internal
    restart: unless-stopped

  websocket:
    build:
      context: .
      dockerfile: Dockerfile.websocket
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
      - ingestor
    environment:
      - MONGO_URI=mongodb://mongodb:27017/EreunaDB
      - VITE_EREUNA_KEY=${VITE_EREUNA_KEY}
      - REDIS_URL=redis://redis:6379/0
    env_file:
      - ./.env
    volumes:
      - ./certs:/certs:ro
    networks:
      - ereuna-network-internal
      - ereuna-network
    restart: unless-stopped

  mongodb:
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db
      - ./mongodb-init:/docker-entrypoint-initdb.d
    environment:
      - MONGO_INITDB_DATABASE=EreunaDB
    networks:
      - ereuna-network-internal
    restart: unless-stopped
    expose:
      - "27017"

networks:
  ereuna-network-internal:
    driver: bridge
    internal: true
  ereuna-network:
    driver: bridge

volumes:
  mongodb_data:
  redis_data:
