auth:
  enabled: false

server:
  http_listen_port: 3100

ingester:
  lifecycler:
    ring:
      kvstore:
        store: inmemory

store:
   filesystem:
     path: /var/lib/loki/db

chunk_store_config:
  max_look_back_period: 12960h

table_manager:
  retention_deletes_enabled: true
  retention_period: 12960h #roughtly 18 months 
