global:
  scrape_interval: 10s
rule_files:
  - rule.yml
alerting:
  alertmanagers:
   - static_configs:
     - targets:
        - alert-manager:9093

scrape_configs:
  - job_name: 'backend'
    scrape_interval: 10s
    metrics_path: /metrics
    static_configs:
      - targets: ['backend:5500']

  - job_name: 'frontend'
    scrape_interval: 10s
    metrics_path: /metrics
    static_configs:
      - targets: ['frontend:443']

  - job_name: 'mongodb'
    scrape_interval: 10s
    metrics_path: /metrics
    static_configs:
      - targets: ['mongodb:27017']
