global:
  scrape_interval: 10s
rule_files:
  - rule.yml
alerting:
  alertmanagers:
   - static_configs:
     - targets:
        - alert-manager:9093

scrape_configs:
  - job_name: 'backend'
    scrape_interval: 10s
    metrics_path: /metrics
    static_configs:
      - targets: ['backend:5500']

  - job_name: 'frontend'
    scrape_interval: 10s
    metrics_path: /metrics
    static_configs:
      - targets: []

  - job_name: 'mongodb'
    scrape_interval: 10s
    metrics_path: /metrics
    static_configs:
      - targets: []

  - job_name: 'websocket'
    scrape_interval: 10s
    metrics_path: /metrics
    static_configs:
      - targets: ['websocket:8000']

  - job_name: 'aggregator'
    scrape_interval: 10s
    metrics_path: /metrics
    static_configs:
      - targets: ['aggregator:8002']

  - job_name: 'ingestor'
    scrape_interval: 10s
    metrics_path: /metrics
    static_configs:
      - targets: ['ingestor:8001']
