apiVersion: v1
kind: Namespace
metadata:
  name: ereuna-prod
  labels:
    name: ereuna-prod
    environment: production
---
apiVersion: v1
kind: Namespace
metadata:
  name: ereuna-monitoring
  labels:
    name: ereuna-monitoring
    environment: production
