# GitHub Actions CI/CD Pipeline for EREUNA Project, not ready yet
#supposed to update the project automatically on push to main branch, update repos in my profile and replace zero downtime using kubernetes (k3s)